# Generated by Django 5.2 on 2025-04-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('symbol_number', models.CharField(max_length=20, unique=True)),
                ('school_name', models.CharField(max_length=100)),
                ('exam_year', models.CharField(max_length=10)),
                ('english', models.FloatField()),
                ('math', models.FloatField()),
                ('nepali', models.FloatField()),
                ('science', models.FloatField()),
                ('health', models.FloatField()),
                ('total', models.FloatField()),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
    ]
